version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: better_auth_postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: better_auth_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # environment:
    #   RABBITMQ_DEFAULT_USER: rabbitmq
    #   RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
